// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZe0k_Xp0l6KJJFk7S_wtjJJZxqcsVpc',
    appId: '1:1030592150346:web:0f4119742158ef2a0adfb3',
    messagingSenderId: '1030592150346',
    projectId: 'phonenumauth-2730d',
    authDomain: 'phonenumauth-2730d.firebaseapp.com',
    storageBucket: 'phonenumauth-2730d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCWl6Hwwtvyyt2SWC2lsGNEkmhVPa8Kg',
    appId: '1:1030592150346:android:44b23315a6246fd60adfb3',
    messagingSenderId: '1030592150346',
    projectId: 'phonenumauth-2730d',
    storageBucket: 'phonenumauth-2730d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2PGieqJlMZPK1tztipcAH1NL6k7lHk0',
    appId: '1:1030592150346:ios:c5ae5e8052b9b0400adfb3',
    messagingSenderId: '1030592150346',
    projectId: 'phonenumauth-2730d',
    storageBucket: 'phonenumauth-2730d.firebasestorage.app',
    iosBundleId: 'com.example.counterCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2PGieqJlMZPK1tztipcAH1NL6k7lHk0',
    appId: '1:1030592150346:ios:c5ae5e8052b9b0400adfb3',
    messagingSenderId: '1030592150346',
    projectId: 'phonenumauth-2730d',
    storageBucket: 'phonenumauth-2730d.firebasestorage.app',
    iosBundleId: 'com.example.counterCubit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNZe0k_Xp0l6KJJFk7S_wtjJJZxqcsVpc',
    appId: '1:1030592150346:web:6541806d3d3fccef0adfb3',
    messagingSenderId: '1030592150346',
    projectId: 'phonenumauth-2730d',
    authDomain: 'phonenumauth-2730d.firebaseapp.com',
    storageBucket: 'phonenumauth-2730d.firebasestorage.app',
  );
}
